### ISSUE TITLE
Embedding source external content

### ISSUE THREAD

**Issue by musinsky** [ProfessionalWiki/ExternalContent#21]
Exist any way how embed source external content (not only markdown). For example, how embed source file(s) from GitHub
```
https://github.com/ProfessionalWiki/ExternalContent/blob/master/tests/TestEnvironment.php
```
to wiki with ExternalContent extension ?

**Comment by JeroenDeDauw** [comment]
At the moment the extension only supports Markdown. We are looking for a development budget to add support for more content types.

**Comment by musinsky** [comment]
OK, understand. And https://github.com/JeroenDeDauw/GitHub extension is dead ?

**Comment by JeroenDeDauw** [comment]
It still works but I am not actively developing it further.
