### ISSUE TITLE
Support code embedding

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/ExternalContent#30]
AC
* Does not get rendered as markdown :)
* Syntax highlighting. Language auto-detection optional
* Fully tested with automated tests. Unit and integration tests where appropriate

**Comment by JeroenDeDauw** [comment]
The plugin system for different renders is already in place

![image](https://github.com/ProfessionalWiki/ExternalContent/assets/146040/470ec62a-8091-45f1-a393-e47c13ce35e6)

**Comment by malberts** [comment]
Syntax highlighting can possibly be done client side using something like:
* https://highlightjs.org/
* https://prismjs.com/

That way we can avoid the [SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight) extension which depends on a Python library.

**Comment by JeroenDeDauw** [comment]
Here is a diagram I created before writing the extension. It's likely somewhat out of date but still conveys the high-level structure: 
![image](https://github.com/ProfessionalWiki/ExternalContent/assets/146040/599bb3c1-7f99-44be-8ce1-64b7cae17512)

For this task you presumably need a new ContentRenderer implementation
