### ISSUE TITLE
Allow all file types by default

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/ExternalContent#33]
With the new code syntax highlighting (https://github.com/ProfessionalWiki/ExternalContent/pull/32) it makes more sense to allow all file types by default.

AC:
* `$wgExternalContentFileExtensionWhitelist` defaults to `[]`
* `[]` should allow all file types

**Comment by JeroenDeDauw** [comment]
Done by https://github.com/ProfessionalWiki/ExternalContent/pull/34. Right @malberts ?
