### ISSUE TITLE
Add config for default Markdown rendering

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/ExternalContent#37]
Follow-up to #30 and https://github.com/ProfessionalWiki/ExternalContent/pull/36#discussion_r1345269540

The default behavior in v1.x is to render all URLs as Markdown. In v2.x with the new code syntax highlighting there is a parameter `lang` for indicating that a file should be shown as code. However, a user might want to render all embedded files as code by default and instead specify only when a file should be rendered as Markdown.

AC:
* [ ] Add config `$wgRenderMarkdownByDefault` with default value `true`. This should be used here: https://github.com/ProfessionalWiki/ExternalContent/blob/357b6dee9797e39abd8276a32aabe2578cfdf565/src/Domain/WikiContentRendererFactory.php#L21-L24
* [ ] Add additional parser function parameter `render` to render a file as Markdown when the above config is `false`. E.g.
```{{#embed:https://github.com/ProfessionalWiki/ExternalContent|render}}```

**Comment by JeroenDeDauw** [comment]
Config is added at https://github.com/ProfessionalWiki/ExternalContent/blob/master/extension.json#L22
