### ISSUE TITLE
Add edit button to bitbucket files

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/ExternalContent#38]
AC:
* Edit button is present for at least code blocks shown via the bitbucket function, ideally also all other bitbucket content
* Button is placed to the left of the copy button and is styled similarly
* Button links to the file on bitbucket

**Comment by malberts** [comment]
This new button should integrate via the Toolbar plugin: https://prismjs.com/plugins/toolbar/
This is already included and is used by the Copy plugin: https://prismjs.com/plugins/copy-to-clipboard/
