### ISSUE TITLE
Add soft wrapping for long lines

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/ExternalContent#57]
![image](https://github.com/ProfessionalWiki/ExternalContent/assets/1428594/d5447726-a8c4-4f7a-a28e-d7d755d7fa10)

It's not possible to scroll to the right by using arrow keys or by selecting and dragging the text.

AC:
* [ ] Add soft wrapping CSS as per https://prismjs.com/plugins/line-numbers/

If there are inconsistencies between code blocks with and without line numbers, then look at https://github.com/PrismJS/prism/issues/3419.

**Comment by JeroenDeDauw** [comment]
I'm not sure about that solution. Isn't wrapping more standard?

**Comment by malberts** [comment]
You're right, and they actually have an example of adding the wrapping with line numbers. We just need to make sure this works correctly with our `showLines` logic.
