### ISSUE TITLE
Unexpected behavior when using Copy button along with showLines parameter

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/ExternalContent#58]
Use this wikitext:
```
{{#embed:https://github.com/ProfessionalWiki/ExternalContent|lang=md|lineNumbers|showLines=1-3,5}}
```

![Screenshot_20231031_141519](https://github.com/ProfessionalWiki/ExternalContent/assets/1428594/d896b435-9582-45ac-b18b-bce8e9aeb5c0)

Then click the Copy button. The copied text is the full file, but with broken whitespace:
![Screenshot_20231031_141702](https://github.com/ProfessionalWiki/ExternalContent/assets/1428594/2032d4f3-b44a-49cd-b3b2-b14040f669d0)

----

The copy button behavior should do one of the following:
1. copy the visible lines
2. copy the original full file correctly

Most likely (1) is more the expected behavior.

**Comment by JeroenDeDauw** [comment]
Yes, should only copy visible lines. Though copying the entire file is already better than copying a messed up version of the entire file.
